In [5]:
from pyESN import ESN
from specializeGraph import *
import numpy as np
from scipy import integrate
import matplotlib.pyplot as plt

In [11]:
def lorentz_deriv(X, t0, sigma=10., beta=8./3, rho=28.0):
    """Compute the time-derivative of a Lorenz system."""
    (x, y, z) = X
    return [sigma * (y - x), x * (rho - z) - y, x * y - beta * z]

x0 = [10, 5, -5]  # starting vector
t = np.linspace(0, 3, 2000)  # two thousand time steps
xt = integrate.odeint(lorentz_deriv, x0, t)

In [17]:
model = ESN(3,3,out_activation=np.tanh)

In [18]:
inputs = xt[:-1,:]
outputs = xt[1:,:]
model.fit(inputs,outputs)

array([[ 1.        ,  0.99996527, -0.99988988],
       [ 0.99999999,  0.9999868 , -0.99986384],
       [ 0.99999999,  0.99999489, -0.99983013],
       ...,
       [-0.99999998, -0.99999701,  1.        ],
       [-0.99999998, -0.99999672,  1.        ],
       [-0.99999997, -0.99999641,  1.        ]])

In [20]:
outputs[-1,:]

array([-9.09090368, -6.61285612, 30.61494808])

In [25]:
model.predict(np.reshape(outputs[-1,:],(1,3)))

array([[-0.76159414, -0.7615925 ,  0.76159416]])