In [125]:
import numpy as np
from scipy import linalg as la
from specializeGraph import *

### Classes of specializations

1. Graphs where the specialization has the same spectral radius
2. Graphs with linearly independent eigenvectors
3. Graphs where the specialization has linearly indep. eigenvectors
4. Graphs where the eigenvalues are a subset of specialized graph spectrum

CONCLUSION:
None of these classes are a subset of any other class

In [126]:
howMany = 3000
n = 4
class1 = []
class2 = []
class3 = []
class4 = []

for i in range(howMany):
    G,base = randomGraph(4)
    sG = specializeGraph(G,base)
    rhoG = spectralRad(laplacian(G))
    rhoSG = spectralRad(laplacian(sG))
    sigmaG,Q = la.eig(laplacian(G))
    sigmaSG,V = la.eig(laplacian(sG))
    sigmaG = np.round(sigmaG,6)
    sigmaSG = np.round(sigmaSG,6)
    subSet = False
    sig = list(sigmaG.copy())
    sigS = list(sigmaSG.copy())
    sub = True
    for i in range(len(sig)):
        
        if sig[i] in sigS:
            sigS.pop(sigS.index(sig[i]))
        else:
            sub = False
            break  
    
    if G.size < sG.size:
        
        if np.isclose(rhoG,rhoSG):
            class1.append((G,base))

        if np.round(la.det(Q),15) != 0:
            class2.append((G,base))

        if np.round(la.det(V),15) != 0:
            class3.append((G,base))

        if sub:
            class4.append((G,base))
        

In [127]:
print("Stable: {}".format(len(class1)))
print("Lin Ind: {}".format(len(class2)))
print("Lin Ind SP: {}".format(len(class3)))
print("Eig Sub: {}".format(len(class4)))

Stable: 256
Lin Ind: 1444
Lin Ind SP: 798
Eig Sub: 219


In [128]:
H = np.reshape(np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]),(4,4))
h = np.array([59, 61, 67, 71])
Hash1 = []
Hash2 = []
Hash3 = []
Hash4 = []
HASH = [Hash1,Hash2,Hash3,Hash4]
CLASS = [class1,class2,class3,class4]
for i in range(len(HASH)):
    for j in range(len(CLASS[i])):
        G,base = CLASS[i][j]
        num = np.prod(H[G==1])*np.prod(h[base])
        HASH[i].append(num)

In [129]:
S1 = set(Hash1)
S2 = set(Hash2)
S3 = set(Hash3)
S4 = set(Hash4)


In [130]:

print("Number in Class1 but not in Class2: {}".format(len(S1.difference(S2))))
print("Number in Class1 but not in Class3: {}".format(len(S1.difference(S3))))
print("Number in Class1 but not in Class4: {}".format(len(S1.difference(S4))))
print("\n")
print("Number in Class2 but not in Class1: {}".format(len(S2.difference(S1))))
print("Number in Class2 but not in Class3: {}".format(len(S2.difference(S3))))
print("Number in Class2 but not in Class4: {}".format(len(S2.difference(S4))))
print("\n")
print("Number in Class3 but not in Class1: {}".format(len(S3.difference(S1))))
print("Number in Class3 but not in Class2: {}".format(len(S3.difference(S2))))
print("Number in Class3 but not in Class4: {}".format(len(S3.difference(S4))))
print("\n")
print("Number in Class4 but not in Class1: {}".format(len(S4.difference(S1))))
print("Number in Class4 but not in Class2: {}".format(len(S4.difference(S2))))
print("Number in Class4 but not in Class3: {}".format(len(S4.difference(S3))))

Number in Class1 but not in Class2: 39
Number in Class1 but not in Class3: 93
Number in Class1 but not in Class4: 47


Number in Class2 but not in Class1: 842
Number in Class2 but not in Class3: 444
Number in Class2 but not in Class4: 879


Number in Class3 but not in Class1: 499
Number in Class3 but not in Class2: 47
Number in Class3 but not in Class4: 510


Number in Class4 but not in Class1: 10
Number in Class4 but not in Class2: 39
Number in Class4 but not in Class3: 67


### Classes of specializations

1. Graphs where the specialization has the same spectral radius
2. Graphs with linearly independent eigenvectors
3. Graphs where the specialization has linearly indep. eigenvectors
4. Graphs where the eigenvalues are a subset of specialized graph spectrum


In [131]:
np.where(np.array(Hash4)==list(S4.difference(S1))[0])

(array([55]),)

In [134]:
G,base = class4[55]
sG = specializeGraph(G,base)
sG = specializeGraph(G,base)
rhoG = spectralRad(laplacian(G))
rhoSG = spectralRad(laplacian(sG))
sigmaG,Q = la.eig(laplacian(G))
sigmaSG,V = la.eig(laplacian(sG))
sigmaG = np.round(sigmaG,14)
sigmaSG = np.round(sigmaSG,14)
print(rhoG,rhoSG)

(2.0000000144333283, 2.618033988749896)


In [133]:
print(sigmaG,sigmaSG)

(array([2.61803399+0.j, 0.38196601+0.j, 0.        +0.j, 0.        +0.j]), array([2.61803399+0.j, 0.38196601+0.j, 1.        +0.j, 0.        +0.j,
       0.        +0.j]))


In [137]:
G,base = class1[0]
print(base)

[2, 1]


array([[0., 1., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.]])