In [14]:
import numpy as np
from scipy import linalg as la
from matplotlib import pyplot as plt
import specializeGraph

In [36]:
def efTrans(A,i,j):
    """
    Parameters:
    -----------
    A (nxn) numpy array: Adjacency Matrix
    i (int): vertex number
    j (int): vertex number
    
    Returns:
    --------
    ef (float): effective transition probability 
                between node i and node j
    """
    
    m,n = A.shape
    s = list(range(n)) #All nodes except i and j
    s.remove(i)
    s.remove(j)
    
    c = [i,j] #Just i and j
    
    #Find the spectral radius
    eig = la.eigvals(A)
    rho = np.max(eig*eig.conjugate())**.5
    
    EF = A[c][:,c] - A[c][:,s].dot(la.inv(A[s][:,s] - rho*np.eye(n-2)).dot(A[s][:,c]))
    return EF[0,1]

In [30]:
A = specializeGraph.randomGraph(10,stronglyCon=1,base=0)

In [40]:
efTrans(A,4,9)

(1.9570656913515048+0j)

In [45]:
M = np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i != j:
            M[i,j] = efTrans(A,i,j)

print(np.round(M-10*A,3))

[[ 0.     1.57  -8.474  1.71  -8.264  1.131  1.079  1.887  0.909  1.377]
 [ 2.648  0.    -7.977  2.359  2.201  1.763  1.487 -7.308  1.339 -7.99 ]
 [ 2.96   2.328  0.    -7.441  2.135  2.046  1.714 -7.116 -8.227 -7.914]
 [ 2.456  2.008  1.894  0.     1.728 -8.335 -8.403  2.275  1.09   1.585]
 [-6.926 -7.688  1.949  2.132  0.     1.788  1.402 -6.794 -8.535  1.957]
 [ 2.908 -7.313 -7.289  2.981 -7.405  0.    -7.987 -6.094  1.712  2.147]
 [-6.165 -6.867 -6.86   3.954  2.814 -7.217  0.     3.605  2.036 -7.215]
 [-7.797  1.864  1.736 -8.15  -7.886 -8.226  1.184  0.     1.081  1.454]
 [ 3.961 -6.539 -6.016 -6.691  3.605 -7.096 -7.502 -5.967  0.    -6.397]
 [-6.753  2.811  2.536  2.604 -7.394  1.97   1.848 -7.063 -8.05   0.   ]]


/Library/Python/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: ComplexWarning: Casting complex values to real discards the imaginary part


In [28]:
c.conjugate

<function conjugate>